[versions]
junit = "5.11.0"

[libraries]
picocli = "info.picocli:picocli:4.7.6"
jansi = "org.fusesource.jansi:jansi:2.4.1"
hamcrest = "org.hamcrest:hamcrest:3.0"
jimfs = "com.google.jimfs:jimfs:1.3.0"

[plugins]
shadow = "com.gradleup.shadow:8.3.0"
